project_id = "dsbfufuqpielvayqlxtw"

[functions.export-agents]
verify_jwt = false

[functions.bulk-import-agents]
verify_jwt = false

[functions.atlas-orchestrator]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.perplexity-search]
verify_jwt = false

[functions.perplexity-meta-search]
verify_jwt = false

[functions.csuite-generate-report]
verify_jwt = false

[functions.atlas-allocate-agents]
verify_jwt = false

[functions.atlas-generate-summary]
verify_jwt = false

[functions.atlas-enterprise-query]
verify_jwt = false

[functions.entrepreneur-validate-idea]
verify_jwt = false

[functions.entrepreneur-growth-optimizer]
verify_jwt = false

[functions.entrepreneur-launch-venture]
verify_jwt = false

[functions.agent-memory]
verify_jwt = false

[functions.atlas-task-processor]
verify_jwt = false

[functions.knowledge-discovery-engine]
verify_jwt = false

[functions.picovoice-access-key]
verify_jwt = false

[functions.veracity-evaluator]
verify_jwt = false

[functions.code-evolution-engine]
verify_jwt = false

[functions.atlas-universal-query]
verify_jwt = false
